#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'togl'


def options(opt):
	# stub
	return


def configure(conf):
	conf.define('TOGL_DLL_EXPORT', 1)

	conf.env.append_unique('DEFINES', [
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead',
		'HAVE_ASTCENC=1',
	])

	# ASTC LDR/HDR runtime texture recompression
	#
	# ASTCENC IS REQUIRED.
	#
	# Required:
	#   - astcenc.h
	#   - libastcenc
	#
	# Debian/Ubuntu:
	#   sudo apt install libastcenc-dev
	#
	# If astcenc is missing, configuration MUST fail.
	conf.check_cc(
		lib='astcenc',
		header_name='astcenc.h',
		uselib_store='ASTCENC',
		mandatory=True
	)


def build(bld):
	source = [
		'linuxwin/dx9asmtogl2.cpp',
		'linuxwin/dxabstract.cpp',
		'linuxwin/glentrypoints.cpp',
		'linuxwin/glmgr.cpp',
		'linuxwin/glmgrbasics.cpp',

		# OSX:
		#'linuxwin/intelglmallocworkaround.cpp',
		#'linuxwin/mach_override.c',

		'linuxwin/cglmtex.cpp',
		'linuxwin/cglmfbo.cpp',
		'linuxwin/cglmprogram.cpp',
		'linuxwin/cglmbuffer.cpp',
		'linuxwin/cglmquery.cpp',
		'linuxwin/asanstubs.cpp',
		'linuxwin/decompress.c',
		'linuxwin/astc_texcompress.cpp',
	]

	if bld.env.DEST_OS == "darwin":
		source += [
			'linuxwin/glmgrcocoa.mm'
		]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	] + bld.env.INCLUDES_SDL2

	defines = []

	# ASTCENC is REQUIRED.
	# Do not make this conditional.
	libs = [
		'tier0',
		'tier1',
		'tier2',
		'vstdlib',
		'mathlib',
		'ASTCENC',
	]

	if bld.env.DEST_OS == "darwin":
		libs += [
			"OPENGL",
			"CARBON"
		]

	install_path = bld.env.LIBDIR

	bld.shlib(
		source=source,
		target=PROJECT_NAME,
		name=PROJECT_NAME,
		features='c cxx',
		includes=includes,
		defines=defines,
		use=libs,
		install_path=install_path,
		subsystem=bld.env.MSVC_SUBSYSTEM,
		idx=bld.get_taskgen_count()
	)
